name: CI - SemaforoIA Pipeline

on:
  push:
    branches: [ main, dev/brillight, dev/Enzo, dev/victor ]
  pull_request:
    branches: [ main ]

jobs:
  quality-and-deploy:
    runs-on: ubuntu-latest
    env:
      PYTHONPYCACHEPREFIX: ${{ github.workspace }}/.cache/python
      PYTHONUTF8: "1"
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4.2.2

      - name: Configurar Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar simulación de la aplicación en consola
        run: python src/app.py

      - name: Ejecutar pruebas unitarias automatizadas
        run: python -m pytest -o cache_dir=.cache/pytest

      - name: Ejecutar análisis de seguridad de código
        run: bandit -r src

      - name: Construir y ejecutar contenedor Docker
        run: |
          docker build -t semaforo-ia:latest .
          docker run --rm semaforo-ia:latest

      - name: Despliegue simulado
        run: echo "Despliegue simulado realizado con éxito"